# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChinaTransformTool
                                 A QGIS plugin
 shp文件坐标系转换工具，支持WGS84\GCJ02\BD09坐标系转换
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-21
        copyright            : (C) 2021 by wudaojian
        email                : 827337743@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ChinaTransformTool class from file ChinaTransformTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .china_transform_tool import ChinaTransformTool
    return ChinaTransformTool(iface)
